# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Unit Tests

on:
  push:
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        timezone: [UTC, America/Los_Angeles, Europe/Berlin, Australia/Sydney]

    steps:
      - uses: actions/checkout@v3

      - name: Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Compile Typescript
        run: npm build

      - name: Run Tests
        run: npm run test:ci 2>&1 | tee $GITHUB_STEP_SUMMARY; exit ${PIPESTATUS[0]}
        env:
          TZ: ${{ matrix.timezone }}
          NODE_OPTIONS: --experimental-vm-modules
